server:
  port: ${port}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          #使用小写服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: business-service-provider #路由的ID
          uri: lb://business-service-provider
          predicates:
            - Path=/b/** # 路由规则
          filters:
            - StripPrefix=1
        - id: user-service-provider #路由的ID
          uri: lb://user-service-provider
          predicates:
            - Path=/u/** # 路由规则
          filters:
            - StripPrefix=1