server:
  port: ${port}

spring:
  aop:
    # cglib代理
    proxy-target-class: true
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${db_host}:${db_port}/${db_database}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${db_user_name}
    password: ${db_password}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 3600000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 0

#myBatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%X{requestId}] [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%X{requestId}] [%thread] %-5level %logger- %msg%n'
