# Tomcat
server:
  port: ${port}

# spring
spring:
  aop:
    proxy-target-class: true


# log
logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%X{requestId}] [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%X{requestId}] [%thread] %-5level %logger- %msg%n'